services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    image: poc-backend
    environment:
      ENV: PROD
      ASPNETCORE_URLS: http://+:8081
      ASPNETCORE_ENVIRONMENT: Production
      Auth__Authority: ${AUTH_AUTHORITY}
      Auth__Audience: ${AUTH_API_CLIENT_ID}
      Cors__SpaOrigin: ${CORS_SPA_ORIGIN}
      KeyVault__VaultUri: ${KEYVAULT_VAULT_URI}
      AZURE_TENANT_ID: ${TENANT_ID}
      AZURE_CLIENT_ID: ${AUTH_API_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AUTH_API_CLIENT_SECRET}
      Agent__Host: ${AGENT_HOST}
      Agent__Port: ${AGENT_PORT}
      Agent__ClientId: ${AUTH_API_CLIENT_ID}
      Agent__ClientSecret: ${AUTH_API_CLIENT_SECRET}
      Agent__TokenEndpoint: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
      Agent__AgentScope: "api://${AUTH_AGENT_CLIENT_ID}/.default"
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - "${BE_PORT}:8081"

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        VITE_OIDC_AUTHORITY: ${VITE_OIDC_AUTHORITY}
        VITE_OIDC_CLIENT_ID: ${VITE_OIDC_CLIENT_ID}
        VITE_OIDC_SCOPE: ${VITE_OIDC_SCOPE}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_OIDC_REDIRECT_URI: ${VITE_OIDC_REDIRECT_URI}
    image: poc-frontend-prod
    depends_on:
      - backend
    ports:
      - "${FE_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
